name: '🏠 Prototype'
labels: 'prototype'
description: I want a new prototype created

body:
  - type: input
    attributes:
      label: Prototype name
      description: |
        It should start with your team name, e.g. `idam-`
      placeholder: |
        idam-prototype
    validations:
      required: true
  - type: input
    attributes:
      label: GitHub team to have access
      description: |
        @hmcts/idam
      placeholder: |
        @hmcts/idam
    validations:
      required: true
